### PR TITLE
Update dependencies with known security vulnerabilities

### PR DESCRIPTION
**Pull request by liliakai**
## Status

Ready for review

## Description of Changes

Fixes Github security warnings about  potential security vulnerabilities in dependencies defined in defined in package-lock.json.

Changes proposed in this pull request:

Update electron, sshpk, macaddress, and lodash to latest.

## Testing

There are no code changes here, only dependency upgrades, so automated testing and perhaps manual smoke testing should be sufficient.

### CODE REVIEW

**Comment by conorsch** [comment]
Rebased on latest master, to include changes pulled in from #141.

**Comment by conorsch** [comment]
Linux builds are broken on this branch; no `.deb` files are created via `make build-deb`. Although the build exits 0, the following error output is displayed:

```
Error: Cannot find module '7zip-bin-linux'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/sunder/node_modules/electron-builder-lib/node_modules/7zip-bin/index.js:15:67)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at _load_zipBin (/sunder/node_modules/electron-builder-lib/out/packager/dirPackager.js:67:22)
    at /sunder/node_modules/electron-builder-lib/src/packager/dirPackager.ts:62:13
```

So it looks like we should preserve the `7zip-bin-linux` dependency in `package-lock.json`.

**Comment by liliakai** [comment]
Aha. Got it. I guess npm was a little too eager to optimize for my osx machine. Also seems like recent versions of electron-builder (and it's newer 7zip dependency) remove these platform-specific modules. 🎉  

As an aside, we should consider switching to yarn for easier and more consistent dependency management.

**Comment by liliakai** [comment]
Another vulnerability surfaced in one of our dependencies today, so I'll update this branch again shortly.

**Comment by conorsch** [comment]
Thanks, @liliakai, will re-review once the new fix is appended!

**Comment by liliakai** [comment]
Updated and ready for review again. This time I verified that make build-deb produced a deb. :)

**Comment by liliakai** [comment]
Just rebased and tested this against latest master. lg2m ✅

**Pull request merged**
